# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

api_login_check:
  path: /api/login_check

songs:
  type: rest
  resource: App\Controller\SongController
  prefix: api
genres:
  type: rest
  resource: App\Controller\GenreController
  prefix: api
artists:
  type: rest
  resource: App\Controller\ArtistController
  prefix: api
playlists:
  type: rest
  resource: App\Controller\PlaylistController
  prefix: api